{
 "title": "harshad",
 "description": "sample dashboard shwoing mqtt, opcua data",
 "time": { "from": "2021-02-18T11:52:00.000Z", "to": "2021-02-18T12:02:00.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "random values",
   "type": "graph",
   "description": "random values generated from nodejs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "rh",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "harshad",
     "query": "SELECT first(\"relativehumidity\") FROM \"autogen\".\"harshad\" WHERE  $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "relativehumidity" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "temp",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "harshad",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "opcua_nodejs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "rh",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opcuanodejs",
     "select": [
      [
       { "params": [ "r" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "temp",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opcuanodejs",
     "select": [
      [
       { "params": [ "t" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "mqtt event based data logging",
   "type": "graph",
   "description": "Data gets logged only when mqtt value is received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "value1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt",
     "select": [
      [
       { "params": [ "value1" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "value1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt",
     "select": [
      [
       { "params": [ "value2" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kepware",
   "type": "graph",
   "description": "Kepware data from 192.168.1.5",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pressure",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kepware",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "temp",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kepware",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "sprayer1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kepware",
     "select": [
      [
       { "params": [ "sprayer1" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "sprayer2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kepware",
     "select": [
      [
       { "params": [ "sprayer2" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "sprayer3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kepware",
     "select": [
      [
       { "params": [ "sprayer3" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "tank1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kepware",
     "select": [
      [
       { "params": [ "tank1" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "tank2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kepware",
     "select": [
      [
       { "params": [ "tank2" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "tank3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kepware",
     "select": [
      [
       { "params": [ "tank3" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "opcuapython",
   "type": "graph",
   "description": "runs on 192.168.1.10 opcua server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "rh",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "opcuapython",
     "select": [
      [
       { "params": [ "rh" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "temp",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opcuapython",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  }
 ]
}